version: 2.1
jobs:
  test-android:
    docker:
      - image: circleci/android:api-30-jdk17
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "build.gradle.kts" }}
      - run:
          name: Change gradlew permissions
          command: chmod +x ./gradlew
      - run:
          name: Run tests
          command: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "build.gradle.kts" }}
workflows:
  version: 2
  build:
    jobs:
      - test-android
